const USER_ACTION_TYPES = {
  SET_FIRSTNAME: "user/SET_FIRSTNAME",
  SET_LASTNAME: "user/SET_LASTNAME",
  SET_EMAIL: "user/SET_EMAIL",
  SET_PASSWORD: "user/SET_PASSWORD",
};

export default USER_ACTION_TYPES;
